### ISSUE TITLE
求教，centos7运行失败，感激不尽

### ISSUE THREAD

**Issue by iqiqiya** [gengchen528/wechatBot#1]
最后一步运行时出错
报错信息如下所示

> [root@instance-2 wechatBot]# npm run start
> 
> > wechatbot@1.0.0 start /www/wwwroot/wechatBot
> > node index.js
> 
> /www/wwwroot/wechatBot/index.js:22
> async function onLogin (user) {
>       ^^^^^^^^
> 
> SyntaxError: Unexpected token function
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.runMain (module.js:611:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:160:9)
> 
> npm ERR! Linux 3.10.0-957.5.1.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "start"
> npm ERR! node v6.16.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! wechatbot@1.0.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the wechatbot@1.0.0 start script 'node index.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the wechatbot package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs wechatbot
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls wechatbot
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /www/wwwroot/wechatBot/npm-debug.log

**Comment by gengchen528** [comment]
node需要10版本以上，你的node不支持async函数，最好安装node v10.15.1版本

**Comment by iqiqiya** [comment]
好的  非常感谢
