### ISSUE TITLE
 wechaty-puppet-puppeteer@^0.17.13 不存在此版本 

### ISSUE THREAD

**Issue by yaderick** [gengchen528/wechatBot#10]

**Comment by gengchen528** [comment]
由于wechaty-puppet-puppeteer@^0.17.13版本没有发布出去，所以需要自行安装一下wechaty-puppet-puppeteer@^0.17.14版本，执行一下 ```npm install wechaty-puppet-puppeteer@^0.17.14  --no-save```即可解决问题
