### ISSUE TITLE
Cannot read property 'say' of null

### ISSUE THREAD

**Issue by wangyingbo** [gengchen528/wechatBot#12]
![image](https://user-images.githubusercontent.com/12741589/59830966-5e0dde00-9373-11e9-9dde-1472eb5ee330.png)

**Comment by gengchen528** [comment]
看一下设置的备注名和昵称对不对，是不是自己微信的好友

**Comment by wangyingbo** [comment]
NAME是备注名称不是微信号是吧？NICKNAME可以随便填吧？
@gengchen528

**Comment by gengchen528** [comment]
> NAME是备注名称不是微信号是吧？NICKNAME可以随便填吧？
> @gengchen528

备注是你给女朋友或者老婆的备注，不是微信号。NICKNAM是女朋友或者老婆的昵称，不能随便填的
