### ISSUE TITLE
main function放在login？

### ISSUE THREAD

**Issue by WongKaiSung** [gengchen528/wechatBot#14]
把main function放在login，第二天发每日微信的时候date还是昨天的（没有更新到）？我需要每天login才能更新日期吗？

**Comment by gengchen528** [comment]
不是这样的，任务执行的时候获取的是当前的日期，这是一个轮循定时任务

**Comment by WongKaiSung** [comment]
可是我拿到的时间是我login的那天的日期 而不是当前的日期 是我哪里写错吗？
