### ISSUE TITLE
自动回复无效

### ISSUE THREAD

**Issue by Notdefind** [gengchen528/wechatBot#15]
AUTOREPLY: true, //自动聊天功能 默认关闭
    AUTOREPLYPERSON: '塑料兄弟(松江吴彦祖)', //指定好友开启机器人聊天功能   指定好友的备注
    AIBOTAPI: 'http://api.tianapi.com/txapi/robot/', //天行机器人API 注册地址https://www.tianapi.com/signup.html?source=474284281
    APIKEY: '726b3****50d3976646114e9f79', //天行机器人apikey，这里奉献上我自己的key，还是建议大家自己申请一下

已开启机器人自动聊天模式
已经设定每日说任务
你的贴心小助理开始工作啦！

不能自动回复信息

**Comment by gengchen528** [comment]
只有指定人给你发消息时才能自动回复，如果还有问题的话可以加群进行交流

**Comment by Notdefind** [comment]
群号多少呢

**Comment by gengchen528** [comment]
项目介绍里有个小助手微信，加它后发送加群 会自动拉你进群

**Comment by Notdefind** [comment]
加过了，未通过

**Comment by gengchen528** [comment]
已解决，我把issue关了
