### ISSUE TITLE
运行不起来，能看看吗

### ISSUE THREAD

**Issue by moling1234** [gengchen528/wechatBot#16]
![image](https://user-images.githubusercontent.com/32126933/59961061-65b0bc80-9504-11e9-9a04-6a4b9dbe86dc.png)

**Comment by yorickshan** [comment]
同问(⊙﹏⊙)b

**Comment by longlou123** [comment]
我也是这问题

**Comment by gengchen528** [comment]
现在把代码重新拉一下应该就可以了

**Comment by gengchen528** [comment]
现在问题已经解决了，wechaty仓库的贡献者已经修复了bug，各位删除node_module 和package-lock.json文件后重新执行 npm install和npm run start 即可
