### ISSUE TITLE
运行npm run start 报错了

### ISSUE THREAD

**Issue by longlou123** [gengchen528/wechatBot#17]
<img width="1061" alt="屏幕快照 2019-06-22 下午4 55 56" src="https://user-images.githubusercontent.com/25996501/59961780-ef658780-950e-11e9-837e-49268f0da61b.png">

**Comment by gengchen528** [comment]
正在排查问题，应该是wechaty那边的bug，解决后会告诉你

**Comment by shwzh** [comment]
同样的问题

![image](https://user-images.githubusercontent.com/25242043/59962484-7d923b80-9518-11e9-9f36-a6323bd5c21d.png)

**Comment by thosebook** [comment]
同样报错  二维码出不来
![Snipaste_2019-06-22_20-19-11](https://user-images.githubusercontent.com/49610549/59963857-6dd02280-952b-11e9-82c7-4c6b44245793.png)

**Comment by thosebook** [comment]
同样的问题...

**Comment by gengchen528** [comment]
现在问题已经解决了，wechaty仓库的贡献者已经修复了bug，各位删除node_module 和package-lock.json文件后重新执行 `npm  install`和`npm run start `即可
