### ISSUE TITLE
每天发送的消息是从哪里获得的？

### ISSUE THREAD

**Issue by c2ch** [gengchen528/wechatBot#19]
每日一句的消息是在哪里可以修改的？

**Comment by gengchen528** [comment]
http://wufazhuce.com/  这个网址

**Comment by c2ch** [comment]
> http://wufazhuce.com/ 这个网址

可以修改为其他网址嘛？

**Comment by gengchen528** [comment]
入股修改的话需要改变爬虫爬取的代码，如果有编程基础可以去修改，没有编程基础的话不建议修改
