### ISSUE TITLE
无法启动 chrome

### ISSUE THREAD

**Issue by wudiansi** [gengchen528/wechatBot#20]
按照说的启动了 但是报错没启动chrome:

11:44:44 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome!
/mnt/wechatBot/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

11:44:44 ERR PuppetPuppeteer initBridge() exception: Error: Failed to launch chrome!
/mnt/wechatBot/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by gengchen528** [comment]
centos下部署错误，参考说明文档中有说明的
```#依赖库
  yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

  #字体
  yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y```

**Comment by wudiansi** [comment]
感谢 已解决
