### ISSUE TITLE
使用bot更改config

### ISSUE THREAD

**Issue by WongKaiSung** [gengchen528/wechatBot#23]
我使用bot更改config里面的资料， 可是只能改一次。

**Comment by gengchen528** [comment]
没有明白你的意思，每次修改config文件后都需要重新执行`npm run start` 才可以生效

**Comment by WongKaiSung** [comment]
对 我就是想问 能不能不重新执行 就可以生效。 因为我想一直用bot改config

**Comment by WongKaiSung** [comment]
1.test:'1'
2找到1 把一改成a

**Comment by WongKaiSung** [comment]
1.test:'1'
2找到1 把一改成a
3.再找到a改成2

我想这样 可是第三步的时候 读到的test依然是1不是a

**Comment by gengchen528** [comment]
非项目本身的问题可以加群后讨论，新增功能不在issues中讨论
