### ISSUE TITLE
无法自动回复

### ISSUE THREAD

**Issue by xwg2015** [gengchen528/wechatBot#25]
项目可以跑来器  自己申请了天行key  但是不会主动回复 怎么回事啊
测试账号备注和昵称都是对的

**Comment by qingyuan0o0** [comment]
暂时还没找到这个分类信息呢

**Comment by gengchen528** [comment]
主动回复需要在配置中开启 并设置好使用的机器人类型

**Comment by fun-ye** [comment]
微信接口不开放，网页版无法登录，为了安全考虑显示

**Comment by gengchen528** [comment]
> 微信接口不开放，网页版无法登录，为了安全考虑显示

这个问题是微信的问题，没法解决的
