### ISSUE TITLE
怎么破，老哥

### ISSUE THREAD

**Issue by XiaoMaoGuai** [gengchen528/wechatBot#4]
![image](https://user-images.githubusercontent.com/5828801/53716538-3ceeb380-3e90-11e9-9163-3b53955a9a49.png)

**Comment by zlzsingle** [comment]
这个应该是微信账号自身的问题

**Comment by gengchen528** [comment]
对的，这个是微信自身的问题，新注册的号目前都是无法登录网页微信，还有如果是小号，在使用过程中不要频繁发消息，会被检测到，所以建议设置频率不要太高

**Comment by li-xiaojun** [comment]
Cannot read property 'say' of null

**Comment by codeXian** [comment]
Cannot read property 'say' of null + 1

**Comment by codeXian** [comment]
@li-xiaojun 我这里发现是名称带特殊符号，找不到联系人导致的

**Comment by li-xiaojun** [comment]
@codeXian 
是的，只要无法找到联系人就会null。

**Comment by gengchen528** [comment]
这个问题有一定概率出现，目前解决办法是修改备注名，用备注名查找用户

**Comment by wbbw007** [comment]
@XiaoMaoGuai 目前有我们有部分API在内测阶段，具有基本的功能，我们愿意对优秀开发者、企业、学生免费开放一部分内测名额，如果您有意愿请打开下面的地址，填写相关信息，我们会审核您的资质，审核通过后将会根据您留下的联系方式联系您
https://tnwdss67qy.jiandaoyun.com/f/5e6ae0032330170006874524
