### ISSUE TITLE
老哥问个问题，怎么查看wechaty log日志

### ISSUE THREAD

**Issue by usersuccess** [gengchen528/wechatBot#5]
老哥问个问题，怎么查看wechaty log日志，我用的ts-node执行的，后台服务器，怎么查看log日志呢
WECHATY_LOG=silly这个默认设置之后呢，node需要配置吗

**Comment by gengchen528** [comment]
你指的日志是什么日志？ 微信聊天记录的日志么？

**Comment by gengchen528** [comment]
> 不是，就是我吧wechaty挂在服务器了，微信报错信息我应该在哪里看呢，服务器后台是没有控制器看log的，我不是很清楚node怎么配置log访问

你如果使用了pm2的话，有输出日志文件路径配置的地方，你可以看一下
