### ISSUE TITLE
centos 6是不行的是吗，我发现装不了puppeteer

### ISSUE THREAD

**Issue by csonchen** [gengchen528/wechatBot#7]

**Comment by gengchen528** [comment]
应该是可以的，puppeteer可能用的是国外的源，下载的比较慢，今天我会更新一下wechaty版本，最新版的puppeteer源以及女改成淘宝的了

**Comment by csonchen** [comment]
> 应该是可以的，puppeteer可能用的是国外的源，下载的比较慢，今天我会更新一下wechaty版本，最新版的puppeteer源以及女改成淘宝的了

![image](https://user-images.githubusercontent.com/5915045/59409025-e75b6880-8de7-11e9-89b6-f6e7e4fc8048.png)

**Comment by gengchen528** [comment]
> > 应该是可以的，puppeteer可能用的是国外的源，下载的比较慢，今天我会更新一下wechaty版本，最新版的puppeteer源以及女改成淘宝的了
> 
> ![image](https://user-images.githubusercontent.com/5915045/59409025-e75b6880-8de7-11e9-89b6-f6e7e4fc8048.png)
你重新拉取一下代码，我上午更新了wechaty的版本，现在下载使用的是淘宝镜像

**Comment by csonchen** [comment]
> > > 应该是可以的，puppeteer可能用的是国外的源，下载的比较慢，今天我会更新一下wechaty版本，最新版的puppeteer源以及女改成淘宝的了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/5915045/59409025-e75b6880-8de7-11e9-89b6-f6e7e4fc8048.png)
> > 你重新拉取一下代码，我上午更新了wechaty的版本，现在下载使用的是淘宝镜像

嗯，我拉过了，但是还是这样，本地没问题，但是我的服务器上面就是不行

**Comment by proshuai** [comment]
同样的问题，怎么破

**Comment by gengchen528** [comment]
执行一下下面代码，然后删除node_module和package-lock.json后重新执行npm install
```
#依赖库
  yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

  #字体
  yum install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
```

**Comment by gengchen528** [comment]
另外目录权限设置一下，现在看来你的目录是没有权限创建的
