### ISSUE TITLE
可以长时间在线吗？

### ISSUE THREAD

**Issue by hfcheng66** [gengchen528/wechatBot#9]
后台是wechaty的web接口吗？ 如果放在服务器上可以长时间（比如1个星期）在线吗？

**Comment by gengchen528** [comment]
可以的，我自己的小号就一直部署在服务器上，我的连续三周都没掉线

**Comment by hfcheng66** [comment]
你的小号手机端也天天使用吗？

**Comment by gengchen528** [comment]
> 你的小号手机端也天天使用吗？

安卓机双开微信，天天在线
